### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by buguang01** [AlanCheen/Alibaba-Nei-Tui-Guide#2]
谢谢你的文章，让我感觉受益非浅。
真想给你发个红包！

**Comment by czn6** [comment]
哈哈哈 可以加我微信发 哈哈哈

**Comment by czn6** [comment]
进阿里了吗？

**Comment by buguang01** [comment]
怎么加你微信啊，阿里，进不去啊。学历太差，工作经验也不太符合吧。

**Comment by czn6** [comment]
https://github.com/AlanCheen/Alibaba-Nei-Tui-Guide/blob/master/wechat.JPG

我微信
